language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: 7
    - php: hhvm
    - php: nightly

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar update --no-interaction --dev

script:
  - php vendor/bin/phpunit -c tests/phpunit.xml
  - vendor/bin/phpcs --standard=ruleset.xml --runtime-set ignore_warnings_on_exit 1 src
